name: CI

on: push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Sync Repository
      uses: wkod/sync-repo@v0.2.0
      with:
      # GitHub public upstream repo
        upstream_repo: https://github.com/Jermolene/TiddlyWiki5.git